# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3
from deutschland.pegel_online import api_client, configuration, schemas
from deutschland.pegel_online.paths.stations_station_timeseries_measurements_json import (  # noqa: E501
    get,
)

from deutschland import pegel_online

from .. import ApiTestMixin


class TestStationsStationTimeseriesMeasurementsJson(ApiTestMixin, unittest.TestCase):
    """
    StationsStationTimeseriesMeasurementsJson unit test stubs
        Zugriff auf die Ressource Measurement  # noqa: E501
    """

    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200


if __name__ == "__main__":
    unittest.main()
